
spring:
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: pharmacy-route
          uri: lb://PHARMACY
          predicates:
            - Path=/pharmacy/**
        - id: order-route
          uri: lb://ORDER  # lb refers to load balanced
          predicates:
            - Path=/order/**
        - id: eureka-route
          uri: lb://localhost:8050
          predicates:
            - Path=/eureka/web


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE