spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: admin
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true